
DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE BOTTLES(
   ID INTEGER PRIMARY KEY   AUTOINCREMENT,
   BRAND        TEXT    NOT NULL,
   PRICE		TEXT,
   VOLUME		FLOAT,
   COUNT		INTEGER
);

INSERT INTO BOTTLES (BRAND, PRICE)
VALUES ('heineken', 3, 0.25, 10);

CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY   AUTOINCREMENT,
    USERNAME        TEXT    NOT NULL,
    ADMIN 			TEXT NOT NULL,
    PASSWORD        TEXT    NOT NULL
);

INSERT INTO USERS (USERNAME, ADMIN, PASSWORD)
VALUES ("chef barman",'admin', 'admin123');