
DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE BOTTLES(
   ID 			INTEGER PRIMARY KEY		AUTOINCREMENT,
   BRAND        TEXT    NOT NULL,
   PRICE		FLOAT,
   VOLUME		FLOAT,
   COUNT		INTEGER
);

INSERT INTO BOTTLES (BRAND, PRICE, VOLUME, COUNT)
VALUES ('heineken', 3, 0.25, 10);

CREATE TABLE USERS(
    ID 				INTEGER PRIMARY KEY	AUTOINCREMENT,
    USERNAME        TEXT    NOT NULL,
    STATUS 			TEXT	NOT NULL,
    PASSWORD        TEXT    NOT NULL
);

INSERT INTO USERS (USERNAME, STATUS, PASSWORD)
VALUES ("chefBarman",'admin', 'admin123');

INSERT INTO USERS (USERNAME, STATUS, PASSWORD)
VALUES ("utilisateurLambda",'user', 'user321');